baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-bs5-lightbox'

[module]
  workspace = "mod-bs5-lightbox.work"
 [[module.imports]]
    path = "github.com/gethinode/hinode"
  [[module.imports]]
    path = "github.com/JorjaFox/mod-bs5-lightbox"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"

[params]
  [modules]
    [modules.bs5-lightbox]
      integration = "optional"
      disableTemplate = false
      state = "async"
  [debugging]
    showJS = true
    showSCSS = true
